disabled_rules: # rule identifiers to exclude from running
  - nesting
  - function_parameter_count
  - line_length
  - multiple_closures_with_trailing_closure
  - identifier_name
  - file_length
opt_in_rules: # some rules are only opt-in
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
included: # paths to include during linting. `--path` is ignored if present.
  - PizzaOrdering
  - PizzaOrderingTests
  - PizzaOrdringUITests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Project/R.generated.swift
  - Sources/Vendor
  - Carthage
